import { GameQuestion } from '../types';

export const gameQuestions: GameQuestion[] = [
    { frase: "Te miro y te enamoro espontaneamente", correcta: "O4", incorrecta1: "O3", incorrecta2: "O2" },
    { frase: "Mauiaba como perro, o ladraba como gato....?", correcta: "V2", incorrecta1: "V3", incorrecta2: "V5" },
    { frase: "Abro los ojos si me dices -Hola mi niño!.", correcta: "O3", incorrecta1: "O4", incorrecta2: "O2" },
    { frase: "Ni aunque me pellizques pienso abrir los ojos.", correcta: "O1", incorrecta1: "O2", incorrecta2: "O3" },
    { frase: "Soy mecanico y estoy arreglando un coche!", correcta: "V5", incorrecta1: "V4", incorrecta2: "V3" },
    { frase: "Eran 6 motoristas, que eran motos, mientras que chocaba un chofer!", correcta: "M6", incorrecta1: "M5", incorrecta2: "M4" },
    { frase: "AMIGO CIGARRO! CINCO EURO!!", correcta: "V3", incorrecta1: "V4", incorrecta2: "V2" },
    { frase: "Eterno y mudo como el recuerdo..Del amor que tú me diste...", correcta: "V1", incorrecta1: "V2", incorrecta2: "O1" },
    { frase: "Si me pides que saque la lengua, la saco.", correcta: "M6", incorrecta1: "M5", incorrecta2: "M4" },
    { frase: "¡Me estás haciendo daño AHÍ! quita la mano! .", correcta: "M5", incorrecta1: "M4", incorrecta2: "M6" },
    { frase: "¡Ay! me haces daño, me voy!.", correcta: "M4", incorrecta1: "M5", incorrecta2: "M3" },
    { frase: "Rígido, con los brazos fuertemente doblados sobre el pecho.", correcta: "M3", incorrecta1: "M4", incorrecta2: "M2" },
    { frase: "Tieso como una tabla, con los brazos estirados y pegados al cuerpo.", correcta: "M2", incorrecta1: "M3", incorrecta2: "M1" },
    { frase: "Ni se inmuta... flácido total, como un muñeco de trapo.", correcta: "M1", incorrecta1: "M2", incorrecta2: "V1" },
    { frase: "Está al loro, mirando el percal, con los ojos como platos.", correcta: "O4", incorrecta1: "O3", incorrecta2: "O2" },
    { frase: "Le digo '¡Eh, colega, espabila!' y abre los ojos un segundo.", correcta: "O3", incorrecta1: "O4", incorrecta2: "O2" },
    { frase: "Tuve que darle un buen pellizco para que abriera los ojos.", correcta: "O2", incorrecta1: "O1", incorrecta2: "O3" },
    { frase: "Ojos cerrados con Loctite. Ni puto caso, ni aunque le duela.", correcta: "O1", incorrecta1: "O2", incorrecta2: "V1" },
    { frase: "El tío controla. Sabe su nombre, que estamos a martes y que esto es un hospital.", correcta: "V5", incorrecta1: "V4", incorrecta2: "M6" },
    { frase: "Está en la parra. Dice que está en la playa y que somos camareros.", correcta: "V4", incorrecta1: "V5", incorrecta2: "V3" },
    { frase: "Le pregunto '¿Qué pasó?' y me dice '¡Moto! ¡Patata! ¡Rojo!'", correcta: "V3", incorrecta1: "V2", incorrecta2: "V4" },
    { frase: "No habla, solo suelta 'Arrrggh... gñññ...' como si se quejara.", correcta: "V2", incorrecta1: "V3", incorrecta2: "V1" },
    { frase: "Calla'o como un muerto. Ni 'mú'. Cero.", correcta: "V1", incorrecta1: "V2", incorrecta2: "O1" },
    { frase: "Le digo 'Levanta dos dedos, bro' y los levanta.", correcta: "M6", incorrecta1: "M5", incorrecta2: "M4" },
    { frase: "Voy a pincharle y el tío, listo, me agarra la mano pa' que pare.", correcta: "M5", incorrecta1: "M4", incorrecta2: "M6" },
    { frase: "Le pellizco el brazo y lo encoge rápido, como si quemara.", correcta: "M4", incorrecta1: "M5", incorrecta2: "M3" },
    { frase: "Se queda tieso al dolor, brazos doblados sobre el pecho, hecho un ovillo.", correcta: "M3", incorrecta1: "M2", incorrecta2: "M4" },
    { frase: "Tieso como un palo. Al dolor, estira los brazos rectos a los lados.", correcta: "M2", incorrecta1: "M3", incorrecta2: "M1" },
    { frase: "Planchado. Es un muñeco de trapo, no mueve ni una pestaña.", correcta: "M1", incorrecta1: "M2", incorrecta2: "V1" },
    { frase: "Está cotilleando todo lo que pasa, no pierde detalle.", correcta: "O4", incorrecta1: "O3", incorrecta2: "V5" },
    { frase: "Habla, pero se cree que soy su primo y que estamos en 1995.", correcta: "V4", incorrecta1: "V5", incorrecta2: "V3" },
    { frase: "Le pregunto qué tal y me grita: '¡NUNCA!'... y ya.", correcta: "V3", incorrecta1: "V4", incorrecta2: "V2" },
    { frase: "Le pido que me apriete la mano y casi me la parte.", correcta: "M6", incorrecta1: "M5", incorrecta2: "M3" },
    { frase: "Le tocas y solo gruñe... 'Ñññññ...'", correcta: "V2", incorrecta1: "V1", incorrecta2: "V3" },
    { frase: "Está con los ojos como un búho, cotilleando todo el cotarro.", correcta: "O4", incorrecta1: "O3", incorrecta2: "V5" },
    { frase: "Estaba frito, pero le dije '¡Eh, que me piro!' y abrió los ojos.", correcta: "O3", incorrecta1: "O4", incorrecta2: "O2" },
    { frase: "Le doy la chapa y nada. Le aprieto el dedo y ahí sí abre los ojos.", correcta: "O2", incorrecta1: "O3", incorrecta2: "O1" },
    { frase: "Cerrado a cal y canto. Le puedes hacer perrerías que no abre un ojo.", correcta: "O1", incorrecta1: "O2", incorrecta2: "M1" },
    { frase: "Le pregunto y lo clava: 'Soy Javi, es lunes y estoy en urgencias'.", correcta: "V5", incorrecta1: "V4", incorrecta2: "M6" },
    { frase: "Me habla, pero está empanado. Me pregunta por su perro y cree que es jueves.", correcta: "V4", incorrecta1: "V5", incorrecta2: "V3" },
    { frase: "Suelta palabras al azar. Le pregunto '¿Cómo estás?' y dice '¡Parking!'", correcta: "V3", incorrecta1: "V4", incorrecta2: "V2" },
    { frase: "Intenta decir algo pero solo le sale un 'aggggghhh... grrr...'", correcta: "V2", incorrecta1: "V1", incorrecta2: "V3" },
    { frase: "Ni 'mú'. Está en mute. Cero sonido.", correcta: "V1", incorrecta1: "V2", incorrecta2: "M1" },
    { frase: "Le digo 'Enséñame el pulgar, en plan OK' y el tío lo hace.", correcta: "M6", incorrecta1: "M5", incorrecta2: "V5" },
    { frase: "Le voy a tocar la cara y me aparta la mano de un guantazo.", correcta: "M5", incorrecta1: "M4", incorrecta2: "M6" },
    { frase: "Le pellizco la pierna y la encoge de golpe, como si le diera calambre.", correcta: "M4", incorrecta1: "M5", incorrecta2: "M3" },
    { frase: "Al dolor, se encoje todo, brazos doblados y duros contra el pecho.", correcta: "M3", incorrecta1: "M2", incorrecta2: "M4" },
    { frase: "Se pone tieso como un poste, estirando los brazos a tope al dolor.", correcta: "M2", incorrecta1: "M3", incorrecta2: "M1" },
    { frase: "Hecho un cromo. No mueve un músculo. Pura gelatina.", correcta: "M1", incorrecta1: "M2", incorrecta2: "O1" },
    { frase: "Me mira, te mira, nos mira. Está al quite de todo.", correcta: "O4", incorrecta1: "O3", incorrecta2: "V5" },
    { frase: "Le hablas y te mira, pero si te callas, cierra los ojos.", correcta: "O3", incorrecta1: "O2", incorrecta2: "O4" },
    { frase: "Solo se queja y gruñe, imposible entenderle.", correcta: "V2", incorrecta1: "V3", incorrecta2: "V1" },
    { frase: "Le pido que guiñe un ojo, y el tío va y lo guiña.", correcta: "M6", incorrecta1: "M5", incorrecta2: "O4" },
    { frase: "Se cree que estoy en su casa y me echa la bronca. Está flipando.", correcta: "V4", incorrecta1: "V5", incorrecta2: "V3" },
    { frase: "Está flipando con las luces del techo, con los ojos abiertos como platos.", correcta: "O4", incorrecta1: "O3", incorrecta2: "V5" },
    { frase: "Estaba KO, pero le pegué un grito al oído y abrió los ojos.", correcta: "O3", incorrecta1: "O2", incorrecta2: "O4" },
    { frase: "Le di un pellizco en la teta y ahí sí abrió los ojos, quejándose.", correcta: "O2", incorrecta1: "O1", incorrecta2: "M4" },
    { frase: "Nada. Kaput. Ojos cerrados pase lo que pase, ni se inmuta.", correcta: "O1", incorrecta1: "O2", incorrecta2: "M1" },
    { frase: "El pavo controla mazo. Sabe su DNI, la fecha y que está en el hospi.", correcta: "V5", incorrecta1: "V4", incorrecta2: "M6" },
    { frase: "Habla, pero está 'empanao'. Dice que estamos en su pueblo y que soy su primo.", correcta: "V4", incorrecta1: "V5", incorrecta2: "V3" },
    { frase: "Le pregunto '¿Duele?' y me salta '¡Bicicleta! ¡Ayer! ¡Verde!'", correcta: "V3", incorrecta1: "V4", incorrecta2: "V2" },
    { frase: "Solo hace 'mmmm... gggghhh...' como un zombi, no vocaliza.", correcta: "V2", incorrecta1: "V1", incorrecta2: "V3" },
    { frase: "No suelta ni pío. Cero patatero. Ni un quejido.", correcta: "V1", incorrecta1: "V2", incorrecta2: "O1" },
    { frase: "Le pido 'haz el signo de la victoria' y el tío va y lo hace.", correcta: "M6", incorrecta1: "M5", incorrecta2: "O4" },
    { frase: "Le aprieto el hombro y me aparta la mano con mala leche, directo al grano.", correcta: "M5", incorrecta1: "M4", incorrecta2: "M6" },
    { frase: "Le pincho el pie y lo quita de golpe, pero sin intentar tocarme.", correcta: "M4", incorrecta1: "M5", incorrecta2: "M3" },
    { frase: "Al dolor, se queda rígido doblando los brazos sobre el pecho, como un culturista.", correcta: "M3", incorrecta1: "M2", incorrecta2: "M4" },
    { frase: "Se pone tieso como un vampiro en su ataúd, brazos estirados y duros.", correcta: "M2", incorrecta1: "M3", incorrecta2: "M1" },
    { frase: "Es un peso muerto. Le puedes hacer de todo que no mueve ni un pelo.", correcta: "M1", incorrecta1: "M2", incorrecta2: "O1" },
    { frase: "Está 'al fresco', mirando a la peña pasar por el pasillo.", correcta: "O4", incorrecta1: "O3", incorrecta2: "M6" },
    { frase: "No me mira, pero le digo '¡Eh, tú!' y me clava los ojos.", correcta: "O3", incorrecta1: "O2", incorrecta2: "O4" },
    { frase: "Me habla, pero no pillo nada. Me dice que la CIA le persigue.", correcta: "V4", incorrecta1: "V5", incorrecta2: "V3" },
    { frase: "Solo balbucea. 'Bubu... gaga...' Imposible.", correcta: "V2", incorrecta1: "V3", incorrecta2: "V1" },
    { frase: "Le digo 'Saca la lengua, como los Rolling' y va y la saca.", correcta: "M6", incorrecta1: "M5", incorrecta2: "V5" },
    { frase: "El bro está en el 'spot', pillando la ola, con los ojos 'on fire'.", correcta: "O4", incorrecta1: "O3", incorrecta2: "V5" },
    { frase: "Estaba 'out', pero le digo '¡Eh, que hay 'swell'!' y abre los ojos.", correcta: "O3", incorrecta1: "O4", incorrecta2: "O2" },
    { frase: "No molaba, pero tuve que darle un 'toque' (dolor) pa' que abriera los ojos.", correcta: "O2", incorrecta1: "O1", incorrecta2: "O3" },
    { frase: "Wipeout total. Ojos cerrados. No pilla ni media onda.", correcta: "O1", incorrecta1: "O2", incorrecta2: "M1" },
    { frase: "Controla la marea. Sabe su nombre, dónde está y el 'mood' (fecha).", correcta: "V5", incorrecta1: "V4", incorrecta2: "M6" },
    { frase: "Habla, pero va en otra dimensión. Cree que esto es un 'skatepark' en Marte.", correcta: "V4", incorrecta1: "V5", incorrecta2: "V3" },
    { frase: "Suelta 'tags' (palabras) sin 'flow'. '¡Arena! ¡Luz! ¡Tabla!'", correcta: "V3", incorrecta1: "V2", incorrecta2: "V4" },
    { frase: "Cero lírica, bro. Solo suelta 'beats' raros... 'Uuuugh... gñññ...'", correcta: "V2", incorrecta1: "V3", incorrecta2: "V1" },
    { frase: "Modo 'mute'. Ni una mala vibra, ni buena. Lienzo en blanco.", correcta: "V1", incorrecta1: "V2", incorrecta2: "O1" },
    { frase: "Pilla la onda. Le digo 'haz el 'shaka' (pulgar y meñique), bro' y lo clava.", correcta: "M6", incorrecta1: "M5", incorrecta2: "V5" },
    { frase: "Le doy un toque chungo y el pavo localiza mi mano y me la quita. Mal rollo.", correcta: "M5", incorrecta1: "M4", incorrecta2: "M6" },
    { frase: "Le pincho el pie y pega el 'tirón' (flexión), pero sin buscarme. Se pira de la ola.", correcta: "M4", incorrecta1: "M5", incorrecta2: "M3" },
    { frase: "Mal 'flow', bro. Se queda 'clavao' al dolor, brazos doblados sobre el pecho.", correcta: "M3", incorrecta1: "M2", incorrecta2: "M4" },
    { frase: "Rollo súper tieso. Estira los brazos al dolor, como una tabla de surf.", correcta: "M2", incorrecta1: "M3", incorrecta2: "M1" },
    { frase: "Cero 'pop'. Es un 'skate' sin ruedas. No se mueve nada. Flacidez total.", correcta: "M1", incorrecta1: "M2", incorrecta2: "O1" },
    { frase: "Está 'chilleando', mirando el paisaje, modo zen total.", correcta: "O4", incorrecta1: "O3", incorrecta2: "O1" },
    { frase: "Estaba en su 'performance', pero le hablas y te mira.", correcta: "O3", incorrecta1: "O2", incorrecta2: "O4" },
    { frase: "Está en un 'sketch' mental. Me habla del color de mi aura y que es un delfín.", correcta: "V4", incorrecta1: "V5", incorrecta2: "V3" },
    { frase: "Solo gruñe, como el 'beat' de un bajo roto.", correcta: "V2", incorrecta1: "V1", incorrecta2: "V3" },
    { frase: "Le digo 'Levanta el pulgar en plan 'like'' y el colega obedece.", correcta: "M6", incorrecta1: "M5", incorrecta2: "M4" },
];